name: sih
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  http: ^1.0.0
  cupertino_icons: ^1.0.8
  animated_splash_screen: ^1.3.0
  lottie: ^3.1.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/welcome.png
    - assets/background.png
    - assets/home.png
    - assets/driver_signup.png
    - assets/user_home.png
    - assets/user_report.png
    - assets/ur.png
    - assets/route.png
    - assets/profile.jpg
    - assets/dtc.json
    - assets/Animation.json
    - assets/headerlogo.png
    - assets/animation1.json
    - assets/404notfound.json
    - assets/animation2.json
